version: '3.8'

services:
  mysql-root:
    image: mysql:latest
    container_name: finance_advisor_instance
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-network

volumes:
  mysql_data:

networks:
  my-network:
